"""Single source of truth for release and API version identities."""

RELEASE_VERSION = "26.09"
RELEASE_LABEL = "v26.09"
PEP440_VERSION = "26.9"
API_VERSION = "3.0.0"
API_SPEC = "RFDS-002"
API_SPEC_VERSION = "1.1"
CONTRACT_SCHEMA_VERSION = "3.0"
VECTOR_SCHEMA_VERSION = "1.1"
RELEASE_CLASS = "D0"
ROBOT_LIBRARY_VERSION = PEP440_VERSION
