"""Production-oriented B&K Precision 8500B Series Python driver.

``evidence.py`` (not imported here to avoid a hard import-order dependency
for callers that only need the core driver) provides an RFDS-008 structured
evidence/logging engine that plugs into ``CommandExecutor`` via the existing
``AuditSink``/``MetricsSink`` protocols in ``diagnostics.py`` and a
``TracingTransport`` wrapper for raw wire-byte capture. See
``docs/logging_and_evidence.md`` and ``BK8500BLibrary/library.py``, which
wires it into every public Robot Framework keyword.
"""
from .async_device import AsyncBK8500B
from .config import DriverConfig, ReconnectPolicy, RetryPolicy, SafetyPolicy
from .device import BK8500B
from .enums import (
    CommandOutcome,
    DynamicMode,
    OperatingMode,
    ProtectionFlag,
    Protocol,
    SessionState,
    TriggerSource,
)
from .exceptions import (
    BK8500BError,
    ChecksumError,
    ConfigurationError,
    ConnectionLostError,
    DeviceError,
    DeviceRejectedCommandError,
    FrameSyncError,
    IndeterminateCommandOutcome,
    InstrumentRangeError,
    InvalidStateTransitionError,
    LegacyProtocolError,
    LockTimeoutError,
    MalformedResponseError,
    PortBusyError,
    ProtectionTrippedError,
    ProtocolError,
    ReadTimeoutError,
    ResponseTooLargeError,
    SCPICommandError,
    SCPIProtocolError,
    TransportError,
    UnsafeOperationError,
    UnsupportedFeatureError,
    UnsupportedModelError,
    WriteTimeoutError,
)
from .measurements import (
    AppliedSetpoint,
    InstrumentCapabilities,
    InstrumentIdentity,
    LEDConfig,
    ListConfig,
    ListRunResult,
    Measurement,
    OCPTestConfig,
    OCPTestResult,
    SafeEnableConfig,
    SafetyToken,
    SCPIErrorEntry,
    SelfTestResult,
    SlewRate,
    TimingTestConfig,
    TimingTestResult,
    TransientConfig,
)
from .status import (
    DeviceStatus,
    DiagnosticSnapshot,
    HealthReport,
    MeasurementSnapshot,
    SafeEnableResult,
)

__version__ = "0.1.0"

__all__ = [
    "BK8500B",
    "AsyncBK8500B",
    "DriverConfig",
    "RetryPolicy",
    "ReconnectPolicy",
    "SafetyPolicy",
    "Protocol",
    "OperatingMode",
    "DynamicMode",
    "TriggerSource",
    "SessionState",
    "CommandOutcome",
    "InstrumentIdentity",
    "InstrumentCapabilities",
    "Measurement",
    "MeasurementSnapshot",
    "AppliedSetpoint",
    "DeviceStatus",
    "DiagnosticSnapshot",
    "HealthReport",
    "SelfTestResult",
    "SCPIErrorEntry",
    "ProtectionFlag",
    "SafetyToken",
    "SlewRate",
    "TransientConfig",
    "LEDConfig",
    "OCPTestConfig",
    "OCPTestResult",
    "TimingTestConfig",
    "TimingTestResult",
    "ListConfig",
    "ListRunResult",
    "SafeEnableConfig",
    "SafeEnableResult",
    "BK8500BError",
    "ConfigurationError",
    "InvalidStateTransitionError",
    "LockTimeoutError",
    "UnsupportedModelError",
    "UnsupportedFeatureError",
    "TransportError",
    "PortBusyError",
    "ConnectionLostError",
    "ReadTimeoutError",
    "WriteTimeoutError",
    "ProtocolError",
    "SCPIProtocolError",
    "LegacyProtocolError",
    "ChecksumError",
    "FrameSyncError",
    "MalformedResponseError",
    "ResponseTooLargeError",
    "DeviceError",
    "SCPICommandError",
    "ProtectionTrippedError",
    "DeviceRejectedCommandError",
    "InstrumentRangeError",
    "UnsafeOperationError",
    "IndeterminateCommandOutcome",
]
