"""RFDS-008 evidence and diagnostics engine for :mod:`bk8500b` / ``rf_bk8500b``.

Every public keyword call in ``BK8500BLibrary`` is recorded as a *run* under
``results/session/rf_bk8500b/<timestamp>_<run_id>/`` (override with the
``RFDS_EVIDENCE_ROOT`` environment variable): one JSON Lines entry per
event/operation/error, redacted arguments, the underlying protocol exchange
(SCPI text or legacy binary frames, hex-encoded), a device-identity snapshot,
and — once ``Disconnect Electronic Load``/``Disconnect All Electronic
Loads``/``Disconnect`` runs — a ``run_summary.json`` + ``evidence_manifest.json``
pair with a SHA-256 hash per artifact. ``Export Diagnostic Bundle`` zips the
whole thing up for troubleshooting.

This module is deliberately complementary to, not a replacement for, this
driver's existing structured-diagnostics infrastructure:

- :mod:`bk8500b.diagnostics` already defines ``AuditSink``/``MetricsSink``
  protocols and an ``AuditEvent`` dataclass that :class:`bk8500b.execution.
  CommandExecutor` calls on every write/query (operation name, risk class,
  outcome, timing). :class:`EvidenceAuditSink`/:class:`EvidenceMetricsSink`
  below *implement* those protocols and forward into this engine, so
  connecting evidence recording is one constructor argument, not a parallel
  system fighting the existing one for the same seam.
- ``BK8500BLibrary._translate`` already centralizes error translation for
  (most) keyword bodies; this module does not touch it. Operation-level
  recording is applied uniformly via a decorator on every ``@keyword`` method
  instead (see ``rf_bk8500b`` integration in ``BK8500BLibrary/library.py`),
  which does not depend on every keyword happening to route through
  ``_translate`` and so cannot silently miss one.
- The pre-existing ``evidence/hardware_conformance/<version>_<port>_<date>/``
  directories elsewhere in this repository (see e.g. rf_bk8500_load) are
  point-in-time archives generated by post-processing a completed Robot
  ``output.xml``. This engine is different: a live, always-on, per-session
  system that also works outside a formal Robot suite run.

Implements the subset of RFDS-008 that makes a concrete troubleshooting
difference for this driver (structured, correlated, redacted, integrity-hashed
evidence). Deliberately out of scope, consistent with the rf_phidget_relay
reference implementation this was adapted from: a shared cross-driver
package (none exists in this repository yet), log rotation/backpressure
policy, cryptographic signing, and literal RFDS-007 error codes (RFDS-007
was not available while writing this; ``category`` below is a pragmatic
mapping of this driver's own exception hierarchy).
"""

from __future__ import annotations

import contextlib
import contextvars
import hashlib
import json
import logging
import os
import platform
import socket
import sys
import threading
import time
import traceback
import uuid
import zipfile
from collections.abc import Iterator, Mapping
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .diagnostics import AuditEvent
from .enums import CommandOutcome
from .transport.base import Transport

SCHEMA_VERSION = "1.0.0"

logger = logging.getLogger("bk8500b.evidence")

_SENSITIVE_KEY_MARKERS = ("password", "secret", "token", "api_key", "apikey", "credential", "auth")

_current_correlation_id: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "bk8500b_correlation_id", default=None
)
_current_operation_id: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "bk8500b_operation_id", default=None
)
_current_suite_id: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "bk8500b_suite_id", default=None
)
_current_test_id: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "bk8500b_test_id", default=None
)
_current_keyword: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "bk8500b_keyword", default=None
)


# ---------------------------------------------------------------------------
# Time, identifiers, JSON safety, redaction
# ---------------------------------------------------------------------------

def _utc_now_iso() -> str:
    now = datetime.now(timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%S.") + f"{now.microsecond // 1000:03d}Z"


def _new_run_id() -> str:
    now = datetime.now(timezone.utc)
    return f"run-{now.strftime('%Y%m%dT%H%M%S')}.{now.microsecond // 1000:03d}Z-{uuid.uuid4().hex[:8]}"


def _json_default(obj: Any) -> Any:
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, (bytes, bytearray)):
        return obj.hex()
    return repr(obj)


def _looks_sensitive(key: str) -> bool:
    lowered = key.lower()
    return any(marker in lowered for marker in _SENSITIVE_KEY_MARKERS)


def _json_safe(value: Any) -> Any:
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, (bytes, bytearray)):
        return value.hex()
    if isinstance(value, Mapping):
        return redact_mapping(value)
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(item) for item in value]
    return repr(value)


def redact_mapping(data: Mapping[str, Any]) -> dict[str, Any]:
    """Redact keys that look sensitive; recurse into nested mappings (RFDS-008 §29.3)."""
    result: dict[str, Any] = {}
    for key, value in data.items():
        if _looks_sensitive(str(key)):
            result[key] = {"value": "<REDACTED>", "redacted": True, "reason": "credential"}
        else:
            result[key] = _json_safe(value)
    return result


def _classify_exception(exc: BaseException) -> str:
    """Approximate error category from this driver's own exception hierarchy.

    RFDS-008 §17 calls for "RFDS error category and code defined by RFDS-007";
    RFDS-007 itself was not available while writing this, so this maps
    ``bk8500b.exceptions`` names to a small stable category set instead.
    """
    name = type(exc).__name__
    if "Configuration" in name or "UnsupportedModel" in name or "UnsupportedFeature" in name:
        return "VALIDATION"
    if "InvalidStateTransition" in name:
        return "STATE"
    if "Protection" in name or "Unsafe" in name:
        return "SAFETY"
    if "Transport" in name or "Timeout" in name or "Indeterminate" in name or "Malformed" in name:
        return "HARDWARE"
    if "Range" in name:
        return "VALIDATION"
    return "UNKNOWN"


def _safe_distribution_version(dist_name: str) -> str | None:
    try:
        import importlib.metadata as importlib_metadata

        return importlib_metadata.version(dist_name)
    except Exception:
        return None


def _safe_module_version(module_name: str) -> str | None:
    try:
        module = __import__(module_name)
        return getattr(module, "__version__", None)
    except Exception:
        return None


def _sanitized_hostname() -> str:
    try:
        return hashlib.sha256(socket.gethostname().encode("utf-8")).hexdigest()[:12]
    except Exception:
        return "UNKNOWN"


# ---------------------------------------------------------------------------
# Operation context handed to callers inside `with run.record_operation(...)`
# ---------------------------------------------------------------------------

class _OperationContext:
    def __init__(self) -> None:
        self.result: Any = None

    def set_result(self, value: Any) -> None:
        self.result = value


class _NullOperationContext:
    def set_result(self, value: Any) -> None:  # pragma: no cover - trivial
        pass


# ---------------------------------------------------------------------------
# EvidenceRun
# ---------------------------------------------------------------------------

class EvidenceRun:
    """Owns one RFDS-008 result directory for one driver session (one alias)."""

    SCHEMA = "rfds.run_summary"

    def __init__(
        self,
        *,
        driver_id: str = "rf_bk8500b",
        activity: str = "session",
        result_root: Path | None = None,
        execution_mode: str = "REAL_HARDWARE",
    ) -> None:
        self.run_id = _new_run_id()
        self.driver_id = driver_id
        self.activity = activity
        self.execution_mode = execution_mode
        base = result_root or Path(os.environ.get("RFDS_EVIDENCE_ROOT", "results"))
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        self.root = base / activity / driver_id / f"{timestamp}_{self.run_id}"
        self._lock = threading.Lock()
        self._sequence: dict[str, int] = {}
        self._operation_counter = 0
        self._error_counter = 0
        self._start_monotonic = time.monotonic()
        self._start_time = _utc_now_iso()
        self._error_count = 0
        self._warning_count = 0
        self._finalized = False
        self._device_identity: dict[str, Any] = {}
        self._make_dirs()
        self._write_environment()
        self.emit_event("RUN_STARTED", f"Evidence run started for driver {driver_id}", level="INFO")

    def _make_dirs(self) -> None:
        for sub in ("events", "protocol", "cleanup", "integrity", "attachments"):
            (self.root / sub).mkdir(parents=True, exist_ok=True)

    def _write_environment(self) -> None:
        payload = {
            "schema": "rfds.environment",
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "timestamp_utc": _utc_now_iso(),
            "python_version": platform.python_version(),
            "python_executable": sys.executable,
            "platform": platform.platform(),
            "host_token": _sanitized_hostname(),
            "robot_framework_version": _safe_module_version("robot"),
            "driver_distribution_version": _safe_distribution_version("robotframework-bk8500b"),
            "driver_source_version": _safe_module_version("bk8500b"),
            "execution_mode": self.execution_mode,
            "clock_synchronization": "UNKNOWN",
        }
        self._write_json(self.root / "environment.json", payload)

    def _write_json(self, path: Path, payload: dict[str, Any]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with self._lock:
            path.write_text(
                json.dumps(payload, indent=2, sort_keys=True, default=_json_default) + "\n",
                encoding="utf-8",
            )

    def _append_jsonl(self, path: Path, stream_key: str, record: dict[str, Any]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with self._lock:
            seq = self._sequence[stream_key] = self._sequence.get(stream_key, 0) + 1
            record = dict(record)
            record["sequence"] = seq
            with path.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(record, ensure_ascii=False, sort_keys=True, default=_json_default) + "\n")

    def emit_event(
        self,
        event_type: str,
        message: str,
        *,
        level: str = "INFO",
        data: Mapping[str, Any] | None = None,
        correlation_id: str | None = None,
        operation_id: str | None = None,
        session_alias: str | None = None,
    ) -> None:
        record = {
            "schema": "rfds.event",
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "producer_id": f"{self.driver_id}:{session_alias or self.driver_id}",
            "timestamp_utc": _utc_now_iso(),
            "monotonic_ns": time.monotonic_ns(),
            "level": level,
            "event_type": event_type,
            "correlation_id": correlation_id or _current_correlation_id.get(),
            "operation_id": operation_id or _current_operation_id.get(),
            "source": {
                "component": "driver",
                "driver_id": self.driver_id,
                "session_alias": session_alias,
                "suite_id": _current_suite_id.get(),
                "test_id": _current_test_id.get(),
                "robot_keyword": _current_keyword.get(),
            },
            "message": message,
            "data": redact_mapping(dict(data or {})),
        }
        self._append_jsonl(self.root / "events" / "events.jsonl", "events", record)
        python_level = {
            "TRACE": logging.DEBUG,
            "DEBUG": logging.DEBUG,
            "INFO": logging.INFO,
            "WARN": logging.WARNING,
            "ERROR": logging.ERROR,
            "CRITICAL": logging.CRITICAL,
        }.get(level, logging.INFO)
        logger.log(python_level, "[%s] %s", event_type, message)
        if level == "WARN":
            self._warning_count += 1
        # ERROR/CRITICAL are not counted here: paired record_error() calls own _error_count.

    @contextlib.contextmanager
    def record_operation(
        self,
        capability: str,
        *,
        arguments: Mapping[str, Any] | None = None,
        session_alias: str | None = None,
    ) -> Iterator[_OperationContext]:
        with self._lock:
            self._operation_counter += 1
            operation_id = f"op-{self._operation_counter:06d}"
        correlation_id = _current_correlation_id.get() or f"corr-{uuid.uuid4().hex[:12]}"
        corr_token = _current_correlation_id.set(correlation_id)
        op_token = _current_operation_id.set(operation_id)
        safe_arguments = redact_mapping(dict(arguments or {}))
        start_monotonic = time.monotonic_ns()
        start_time = _utc_now_iso()
        self.emit_event(
            "OPERATION_STARTED", f"{capability} started", level="DEBUG",
            correlation_id=correlation_id, operation_id=operation_id,
            data={"arguments": safe_arguments}, session_alias=session_alias,
        )
        ctx = _OperationContext()
        status = "PASS"
        error_summary: str | None = None
        try:
            yield ctx
        except Exception as exc:
            status = "FAIL"
            error_summary = f"{type(exc).__name__}: {exc}"
            self.record_error(
                exc, correlation_id=correlation_id, operation_id=operation_id,
                capability=capability, session_alias=session_alias,
            )
            raise
        finally:
            duration_s = (time.monotonic_ns() - start_monotonic) / 1e9
            record = {
                "schema": "rfds.operation",
                "schema_version": SCHEMA_VERSION,
                "run_id": self.run_id,
                "operation_id": operation_id,
                "correlation_id": correlation_id,
                "capability": capability,
                "session_alias": session_alias,
                "arguments": safe_arguments,
                "start_timestamp_utc": start_time,
                "end_timestamp_utc": _utc_now_iso(),
                "duration_s": round(duration_s, 6),
                "result": _json_safe(ctx.result) if status == "PASS" else None,
                "status": status,
                "error_summary": error_summary,
            }
            self._append_jsonl(self.root / "events" / "operations.jsonl", "operations", record)
            self.emit_event(
                "OPERATION_COMPLETED" if status == "PASS" else "OPERATION_FAILED",
                f"{capability} {'completed' if status == 'PASS' else 'failed'} in {duration_s:.4f}s",
                level="INFO" if status == "PASS" else "ERROR",
                correlation_id=correlation_id, operation_id=operation_id, session_alias=session_alias,
            )
            _current_correlation_id.reset(corr_token)
            _current_operation_id.reset(op_token)

    def log_protocol(
        self,
        direction: str,
        transport: str,
        operation_text: str,
        *,
        session_alias: str | None = None,
    ) -> None:
        """Record one outbound/inbound protocol exchange (SCPI text or hex-encoded legacy frame)."""
        if direction not in ("outbound", "inbound"):
            raise ValueError("direction must be 'outbound' or 'inbound'")
        exchange_id = f"pex-{uuid.uuid4().hex[:10]}"
        record = {
            "schema": "rfds.protocol_exchange",
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "protocol_exchange_id": exchange_id,
            "operation_id": _current_operation_id.get(),
            "correlation_id": _current_correlation_id.get(),
            "timestamp_utc": _utc_now_iso(),
            "transport": transport,
            "direction": direction,
            "session_alias": session_alias,
            "operation": operation_text,
        }
        self._append_jsonl(self.root / "protocol" / "exchanges.jsonl", "protocol_exchanges", record)
        trace_path = self.root / "protocol" / f"{direction}_trace.log"
        with self._lock, trace_path.open("a", encoding="utf-8") as handle:
            handle.write(f"{record['timestamp_utc']} [{exchange_id}] {operation_text}\n")

    def record_error(
        self,
        exc: BaseException,
        *,
        correlation_id: str | None = None,
        operation_id: str | None = None,
        capability: str | None = None,
        session_alias: str | None = None,
        recoverable: bool | None = None,
    ) -> None:
        with self._lock:
            self._error_counter += 1
            error_id = f"err-{self._error_counter:06d}"
        record = {
            "schema": "rfds.error",
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "error_id": error_id,
            "timestamp_utc": _utc_now_iso(),
            "correlation_id": correlation_id or _current_correlation_id.get(),
            "operation_id": operation_id or _current_operation_id.get(),
            "capability": capability,
            "session_alias": session_alias,
            "category": _classify_exception(exc),
            "exception_type": type(exc).__qualname__,
            "message": str(exc),
            "traceback": traceback.format_exc(),
            "recoverable": recoverable,
        }
        self._append_jsonl(self.root / "events" / "errors.jsonl", "errors", record)
        self._error_count += 1
        logger.error("[%s] %s (%s): %s", error_id, capability or "?", type(exc).__name__, exc)

    def record_device_identity(self, **fields: Any) -> None:
        self._device_identity.update({key: value for key, value in fields.items() if value is not None})
        payload = {
            "schema": "rfds.device_identity",
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "timestamp_utc": _utc_now_iso(),
            **self._device_identity,
        }
        self._write_json(self.root / "device_identity.json", payload)

    def _write_manifest(self) -> None:
        skip_names = {"evidence_manifest.json", "checksums.sha256"}
        entries = []
        for path in sorted(self.root.rglob("*")):
            if path.is_dir() or path.name in skip_names:
                continue
            relative = path.relative_to(self.root)
            data = path.read_bytes()
            entries.append(
                {
                    "path": str(relative).replace(os.sep, "/"),
                    "role": _role_for(relative),
                    "size_bytes": len(data),
                    "sha256": hashlib.sha256(data).hexdigest(),
                }
            )
        manifest = {
            "schema": "rfds.evidence_manifest",
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "generated_timestamp_utc": _utc_now_iso(),
            "artifact_count": len(entries),
            "artifacts": entries,
        }
        self._write_json(self.root / "evidence_manifest.json", manifest)
        checksum_path = self.root / "integrity" / "checksums.sha256"
        checksum_path.parent.mkdir(parents=True, exist_ok=True)
        with self._lock:
            checksum_path.write_text(
                "".join(f"{entry['sha256']}  {entry['path']}\n" for entry in entries), encoding="utf-8"
            )

    def finalize(self, status: str = "PASS") -> Path:
        if self._finalized:
            return self.root
        self.emit_event("RUN_FINISHING", f"Evidence run finalizing with status {status}", level="INFO")
        duration_s = time.monotonic() - self._start_monotonic
        summary = {
            "schema": self.SCHEMA,
            "schema_version": SCHEMA_VERSION,
            "run_id": self.run_id,
            "activity": self.activity,
            "driver_id": self.driver_id,
            "start_timestamp_utc": self._start_time,
            "end_timestamp_utc": _utc_now_iso(),
            "duration_s": round(duration_s, 3),
            "execution_mode": self.execution_mode,
            "final_status": status,
            "error_count": self._error_count,
            "warning_count": self._warning_count,
            "dropped_events": 0,
            "evidence_completeness": "COMPLETE",
            "device_identity_reference": "device_identity.json" if self._device_identity else None,
            "result_root": str(self.root),
        }
        self._write_json(self.root / "run_summary.json", summary)
        self._write_markdown_summary(summary)
        self._write_manifest()
        self._finalized = True
        return self.root

    def _write_markdown_summary(self, summary: dict[str, Any]) -> None:
        lines = [
            f"# Evidence run summary — {summary['driver_id']}",
            "",
            f"- Run ID: `{summary['run_id']}`",
            f"- Activity: {summary['activity']}",
            f"- Execution mode: {summary['execution_mode']}",
            f"- Started: {summary['start_timestamp_utc']}",
            f"- Finished: {summary['end_timestamp_utc']}",
            f"- Duration: {summary['duration_s']} s",
            f"- Final status: **{summary['final_status']}**",
            f"- Errors: {summary['error_count']}, Warnings: {summary['warning_count']}",
            f"- Evidence completeness: {summary['evidence_completeness']}",
            "",
            "Generated from `run_summary.json`. See `events/operations.jsonl` for every keyword",
            "call this run made, `events/errors.jsonl` for failures, and `protocol/exchanges.jsonl`",
            "for the underlying SCPI/legacy-frame exchange, in the order they happened.",
            "",
        ]
        (self.root / "run_summary.md").write_text("\n".join(lines), encoding="utf-8")

    def export_diagnostic_bundle(self, destination: str | None = None) -> str:
        self._write_manifest()
        if destination:
            zip_path = Path(destination)
            zip_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            zip_path = self.root.parent / f"{self.root.name}_diagnostic_bundle.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for path in sorted(self.root.rglob("*")):
                if path.is_file():
                    archive.write(path, arcname=str(Path(self.root.name) / path.relative_to(self.root)))
        self.emit_event("DIAGNOSTIC_BUNDLE_EXPORTED", f"Diagnostic bundle written to {zip_path}", level="INFO")
        return str(zip_path)


_ROLE_BY_NAME = {
    "run_summary.json": "AUTHORITATIVE_RESULT",
    "run_summary.md": "DERIVED_REPORT",
    "environment.json": "IDENTITY",
    "device_identity.json": "IDENTITY",
}


def _role_for(relative_path: Path) -> str:
    name = relative_path.name
    if name in _ROLE_BY_NAME:
        return _ROLE_BY_NAME[name]
    parts = relative_path.parts
    if parts and parts[0] == "protocol":
        return "RAW_OBSERVATION"
    if relative_path.suffix == ".jsonl":
        return "STRUCTURED_EVENT"
    if parts and parts[0] == "integrity":
        return "INTEGRITY"
    return "DERIVED_REPORT"


class NullEvidenceRun:
    """Used when ``evidence_enabled=False``: same interface, writes nothing to disk."""

    run_id: str | None = None

    @contextlib.contextmanager
    def record_operation(
        self,
        capability: str,
        *,
        arguments: Mapping[str, Any] | None = None,
        session_alias: str | None = None,
    ) -> Iterator[_NullOperationContext]:
        logger.debug("%s(%s)", capability, dict(arguments or {}))
        yield _NullOperationContext()

    def emit_event(self, *_args: Any, **_kwargs: Any) -> None:
        pass

    def log_protocol(self, *_args: Any, **_kwargs: Any) -> None:
        pass

    def record_error(self, exc: BaseException, **_kwargs: Any) -> None:
        logger.error("%s: %s", type(exc).__name__, exc)

    def record_device_identity(self, **_kwargs: Any) -> None:
        pass

    def finalize(self, status: str = "PASS") -> None:
        return None

    def export_diagnostic_bundle(self, destination: str | None = None) -> None:
        logger.warning("Diagnostic bundle requested but evidence_enabled=False; nothing was recorded.")
        return None


# ---------------------------------------------------------------------------
# Integration with bk8500b.diagnostics.AuditSink / MetricsSink and
# bk8500b.transport.base.Transport — this is the driver-specific adapter
# layer that makes this evidence engine plug directly into the existing
# CommandExecutor seam instead of duplicating it.
# ---------------------------------------------------------------------------

class EvidenceAuditSink:
    """Implements :class:`bk8500b.diagnostics.AuditSink`.

    Forwards every :class:`AuditEvent` the executor already produces (one per
    write/query transaction: operation name, risk class, outcome, detail,
    context) into the evidence run as a structured event.
    """

    def __init__(self, run: EvidenceRun | NullEvidenceRun, *, session_alias: str | None = None) -> None:
        self._run = run
        self._session_alias = session_alias

    def record(self, event: AuditEvent) -> None:
        level = "ERROR" if event.outcome in (
            CommandOutcome.FAILED_NOT_SENT,
            CommandOutcome.OUTCOME_INDETERMINATE,
        ) else "INFO"
        self._run.emit_event(
            f"AUDIT_{event.operation.upper()}",
            f"{event.operation}: {event.detail}",
            level=level,
            data={
                "audit_event_id": event.event_id,
                "risk": event.risk.value,
                "outcome": event.outcome.value,
                "context": dict(event.context),
            },
            session_alias=self._session_alias,
        )


class EvidenceMetricsSink:
    """Implements :class:`bk8500b.diagnostics.MetricsSink`; forwards counters as DEBUG events."""

    def __init__(self, run: EvidenceRun | NullEvidenceRun, *, session_alias: str | None = None) -> None:
        self._run = run
        self._session_alias = session_alias

    def increment(self, name: str, value: int = 1, **labels: str) -> None:
        self._run.emit_event(
            "METRIC_INCREMENT", f"{name} +{value}", level="TRACE",
            data={"name": name, "value": value, **labels}, session_alias=self._session_alias,
        )

    def observe(self, name: str, value: float, **labels: str) -> None:
        self._run.emit_event(
            "METRIC_OBSERVE", f"{name}={value}", level="TRACE",
            data={"name": name, "value": value, **labels}, session_alias=self._session_alias,
        )


class TracingTransport:
    """Wraps a real :class:`Transport` to log raw bytes at the wire boundary.

    ``AuditEvent`` above carries the *outcome* of a transaction (operation
    name, risk, timing) but not the literal bytes sent/received — this class
    is the true RFDS-019 protocol-boundary observation point: every
    ``write``/``read``/``read_until`` call is traced as a hex-encoded payload
    (safe for both SCPI ASCII and the 26-byte legacy binary frame codec)
    before being forwarded unchanged to the wrapped transport.
    """

    def __init__(self, inner: Transport, run: EvidenceRun | NullEvidenceRun, *, session_alias: str | None = None) -> None:
        self._inner = inner
        self._run = run
        self._session_alias = session_alias

    @property
    def is_open(self) -> bool:
        return self._inner.is_open

    def open(self) -> None:
        self._inner.open()

    def close(self) -> None:
        self._inner.close()

    def write(self, data: bytes, *, timeout_s: float | None = None) -> int:
        self._run.log_protocol(
            "outbound", "serial",
            f"write {len(data)}B: {data.hex()} (ascii={data!r})",
            session_alias=self._session_alias,
        )
        return self._inner.write(data, timeout_s=timeout_s)

    def read(self, size: int, *, timeout_s: float | None = None) -> bytes:
        result = self._inner.read(size, timeout_s=timeout_s)
        self._run.log_protocol(
            "inbound", "serial",
            f"read {len(result)}B: {result.hex()} (ascii={result!r})",
            session_alias=self._session_alias,
        )
        return result

    def read_until(self, terminator: bytes, *, maximum_bytes: int, timeout_s: float | None = None) -> bytes:
        result = self._inner.read_until(terminator, maximum_bytes=maximum_bytes, timeout_s=timeout_s)
        self._run.log_protocol(
            "inbound", "serial",
            f"read_until {terminator!r} -> {len(result)}B: {result.hex()} (ascii={result!r})",
            session_alias=self._session_alias,
        )
        return result

    def reset_input_buffer(self) -> None:
        self._inner.reset_input_buffer()

    def reset_output_buffer(self) -> None:
        self._inner.reset_output_buffer()


class EvidenceListener:
    """Register with ``--listener bk8500b.evidence.EvidenceListener`` to correlate
    events with the active Robot suite/test/keyword. Entirely optional."""

    ROBOT_LISTENER_API_VERSION = 3

    def start_suite(self, data: Any, result: Any) -> None:
        _current_suite_id.set(getattr(data, "longname", str(data)))

    def end_suite(self, data: Any, result: Any) -> None:
        _current_suite_id.set(None)

    def start_test(self, data: Any, result: Any) -> None:
        _current_test_id.set(getattr(data, "longname", str(data)))

    def end_test(self, data: Any, result: Any) -> None:
        _current_test_id.set(None)

    def start_keyword(self, data: Any, result: Any) -> None:
        _current_keyword.set(getattr(data, "name", str(data)))

    def end_keyword(self, data: Any, result: Any) -> None:
        _current_keyword.set(None)


__all__ = [
    "SCHEMA_VERSION",
    "EvidenceRun",
    "NullEvidenceRun",
    "EvidenceAuditSink",
    "EvidenceMetricsSink",
    "TracingTransport",
    "EvidenceListener",
    "redact_mapping",
]
