"""Build the project-standard versioned ZIP archive."""
from __future__ import annotations

import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED_DIRS = {
    ".git",
    ".venv",
    ".idea",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "__pycache__",
    "build",
    "results",
    "robot-results",
    "dryrun-results",
}
EXCLUDED_FILES = {".coverage", "output.xml", "log.html", "report.html"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}


def should_include(path: Path) -> bool:
    relative = path.relative_to(ROOT)
    if any(part in EXCLUDED_DIRS or part.endswith(".egg-info") for part in relative.parts):
        return False
    return path.name not in EXCLUDED_FILES and path.suffix not in EXCLUDED_SUFFIXES



def generate_package_manifest() -> None:
    """Write a human-readable inventory of all release files."""
    manifest = ROOT / "PACKAGE_CONTENTS.md"
    # Ensure the manifest is part of its own inventory.
    manifest.touch(exist_ok=True)
    files = sorted(
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*")
        if path.is_file() and should_include(path)
    )
    lines = [
        "# Package Contents",
        "",
        "This manifest is generated by `scripts/build_release.py` for the current release.",
        "Temporary environments, caches, IDE metadata, build work directories, and Robot result files are intentionally excluded.",
        "",
        f"**Included files:** {len(files)}",
        "",
    ]
    lines.extend(f"- `{name}`" for name in files)
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")

def main() -> int:
    if ROOT.name != "rf_bk8500b":
        raise SystemExit(f"Release root must be rf_bk8500b, found {ROOT.name}")

    subprocess.run([sys.executable, str(ROOT / "scripts" / "verify_project_structure.py")], check=True)
    subprocess.run([sys.executable, str(ROOT / "scripts" / "verify_ai_contract.py")], check=True)

    generate_package_manifest()

    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    destination = ROOT.parent / f"rf_bk8500b_v{version}.zip"
    destination.unlink(missing_ok=True)

    files = [path for path in ROOT.rglob("*") if path.is_file() and should_include(path)]
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(files):
            archive.write(path, Path(ROOT.name) / path.relative_to(ROOT))

    with zipfile.ZipFile(destination) as archive:
        roots = {name.split("/", 1)[0] for name in archive.namelist() if name}
        if roots != {"rf_bk8500b"}:
            raise RuntimeError(f"Invalid archive roots: {sorted(roots)}")
        if len(archive.namelist()) != len(files):
            raise RuntimeError("Archive file count does not match source file count")

    print(f"Created {destination}")
    print(f"Included {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
